#!/usr/bin/python3
# the idea of this script is to take a list of subdomains (generated by snows_recon for example) and do a web recon

import sys
import pyfiglet

ascii_banner = pyfiglet.figlet_format("snows_recon_web")
print(ascii_banner)


def help_menu():
	text = """This tool executes basic web enumeration
		Usage: ./snows_recon_web.py [subdomain_list]
	"""
	print(text)
	
try:
	subdomain_file = sys.argv[1]
except:
	help_menu()
	sys.exit()
	
# gospider
# gobuster
# nikto
# xsssniper
